spring:
  application:
    name: users-service
  data:
    jdbc:
      dialect: h2
      repositories:
        enabled: true
  datasource:
    url: jdbc:h2:file:~/test.db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8082
#debug: true